dist: xenial
os: linux
services:
  - postgresql
before_script:
  - psql -c 'create database queries_challenge;' -U postgres
language: node_js
node_js:
  - 14
install:
  - yarn install
script:
  - yarn test
