version: "3.3"

services:
  database-desafio5:
    image: postgres
    container_name: database-desafio5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: 
    driver: local